language: python
python:
  - "2.7"
  - "3.4"

env:
  - SPHINX_VERSION=1.2.3
  - SPHINX_VERSION=1.3b3
  - SPHINX_VERSION=dev

install:
  - pip install coveralls --use-mirrors
  - pip install --allow-external Sphinx --allow-unverified Sphinx -q Sphinx==$SPHINX_VERSION
  - python setup.py install

before_script:
  - git config --global user.email "nathan+travis@yergler.net"
  - git config --global user.name "Travis Build"

script:
  - coverage run --source=tut setup.py test

after_success:
  - coveralls
